cw01 sleep add

diff --git a/.github/workflows/01-building-blocks-inna.yaml b/.github/workflows/01-building-blocks-inna.yaml
--- a/.github/workflows/01-building-blocks-inna.yaml
+++ b/.github/workflows/01-building-blocks-inna.yaml
@@ -5,12 +5,25 @@ on:
 
 jobs:
   echo-hello:
+    name: "Hello"
     runs-on: ubuntu-latest
     steps:
       - name: Say hello
-        run: echo "Hello, World!"
+        run: |
+          echo "Hello, World!"
+          sleep 10
 
   echo-goodbye:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Failed step
+        run: |
+          echo "I will fail"
+          exit 1  # dowolny kod != 0 spowoduje błąd kroku
+      - name: Say goodbye
+        run: echo "Goodbye!"
+
+  trzeci-job:
     runs-on: ubuntu-latest
     steps:
       - name: Failed step
